config/routes.rb
DbcOverflow::Application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, :except => [:destroy]
  resources :questions do
    resources :answers, :except => [:index, :show]
  end

  root to: "questions#index"

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :content
  belongs_to :user
  belongs_to :question

  validates :content, :presence => true, :length => { :maximum => 1000 }
  validates :user, :presence => true
  validates :question, :presence => true
end

app/models/question.rb
class Question < ActiveRecord::Base

  attr_accessible :title, :content

  belongs_to :user
  has_many :answers

  validates :title, :presence => true, :length => {:minimum => 5, :maximum => 100 }
  validates :content, :presence => true, :length => {:minimum => 5 }
  validates :user, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :questions
  has_many :answers
  
  EMAIL_REGEXP = /^[_a-z0-9A-Z-]+(\.[_a-z0-9A-Z-]+)*@[a-z0-9A-Z-]+(\.[a-z0-9A-Z-]+)*(\.[a-zA-Z]{2,4})$/
  attr_accessible :name, :email, :password
  has_secure_password

  validates :name, :presence => true, :length => { :minimum => 3, :maximum => 50 }
  validates :email, :presence => true, 
            :format => { :with => EMAIL_REGEXP }, 
            uniqueness: { case_sensitive: false }
  validates :password, :presence => true, :length => { :minimum => 6 }

  before_save :downcase_email

  def downcase_email
    self.email = self.email.downcase
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_filter :find_question

  # def new
  #   @answer = Answer.new
  # end

  def create
    @answer = @question.answers.build(:content => params[:answer][:content])
    @answer.user = current_user
    @user = current_user

    if @answer.save
      render :json => {:answer => @answer, :user => @user }
    else
      render :json => @answer.errors.full_messages.join(","),
                      :status => :unprocessable_entity
    end
  end

  def destroy
    answer = Answer.find(params[:id])
    answer.destroy
    render :json => {}
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def login(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate!
    redirect_to new_session_path if current_user.blank?
  end

  def sign_out
    session[:user_id] = nil
  end

  helper_method :current_user
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.order("created_at DESC")
  end

  def show
    @question = Question.find(params[:id])
    @answers = Answer.where('question_id = ?', @question.id)
  end

  def new
    if current_user
      @question = Question.new
    else
      redirect_to new_session_path
    end 
  end

  def create
    @question = Question.new(params[:question])
    @question.user = current_user
    if @question.save
      redirect_to question_path(@question)
    else 
      flash.now[:alert] = @question.errors.full_messages.join(",")
      render :new
    end
  end

  def destroy
    question = Question.find(params[:id])
    question.destroy
    render :json => {}
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new 
  end

  def create
    @user = User.find_by_email(params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      login(@user)
      redirect_to root_path
    else
      render :new
    end  
  end

  def destroy
    sign_out
    flash[:notice] = "You've been logged out."
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new params[:user]
    if @user.save
      login(@user)
      redirect_to root_path
    else
      render :new
    end
    
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/new.html.erb
<%= form_for [@question, @answer] do |f| %>
<div>
  <%= f.label :content %><br>
  <%= f.text_area :content %>
</div>
  <div>
    <%= f.submit "Submit Answer" %>
  </div>
<% end %>

<%= link_to "Back to Question", question_path(@question) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CupOverflow</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "CupOverflow", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <% if current_user %>
            <li><%= link_to "Hey " + current_user.name, user_path(current_user) %></li>
            <li><%= link_to "Signout", session_path(session[:user_id]), :method => :delete %></li>
          <% else %>
            <%= link_to "Signup", new_user_path %>
            <%= link_to "Signin", new_session_path %>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

<div class="container">
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "alert alert-#{key}") %>
  <% end %>

  <%= yield %>
</div>
  
</body>
</html>

app/views/questions/index.html.erb
<h1>Here your cup runneth over</h1>

<%= link_to "Add a Question", new_question_path, :class => "btn btn-large btn-success" %>

<ul class="questions">
<% @questions.each do |inquisition| %>
  <li><%= link_to inquisition.title, inquisition %>
    <% if inquisition.user == current_user %>
      <%= link_to '', question_path(inquisition), 
          :class => 'icon-remove', :remote => true, :method => 'delete' %>
    <% end %>
  </li>
<% end %>
</ul>

app/views/questions/new.html.erb
<h1>Add a Question</h1>

<%= form_for @question do |f| %>
<div>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :content %>
  <%= f.text_area :content %><br>
  <%= f.submit "Add Question" %>
</div>
<% end %>

<%= link_to "Back to Index", root_path %>

app/views/questions/show.html.erb
<h1>Q: <%= @question.title %></h1>
<p><%= @question.content %></p>

<%= form_for [@question, Answer.new], :remote => true do |f| %>
  <div>
    <%= f.label :content %>
    <%= f.text_area :content, :placeholder => "Answer this question" %><br>
    <%= f.submit "Submit Answer", :class => "btn btn-large btn-primary" %>
  </div>
<% end %>

<ul class="answers">
  <% @answers.each do |answer| %>
    <li>
      <%= answer.content %>
      Posted by: <%= answer.user.name %> 
      <% if answer.user == current_user %>
      <%= link_to '', question_answer_path(@question, answer), 
          :class => 'icon-remove', :remote => true, :method => 'delete' %>
      <% end %>
    </li>
  <% end %>
</ul>

<%= link_to "Back to Index", root_path %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<div>
  <%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %><br>
  <%= f.submit "Sign up" %>
</div>
<% end %>

app/views/users/show.html.erb
<h1>Profile Page for <%= @user.name %></h1>
<p>Not much yet..</p>